
const flaglabel = {
  AUD : { id: 1, src: "'../images/flags/australia.png'", name: 'Australian Dollar' },
  BRL : { id: 2, src: './flags/brazil.png', name: 'Brazilian Real' },
  BGN : { id: 3, src: './flags/bulgaria.png', name: 'Bulgarian Levl' },
  CAD : { id: 4, src: './flags/canada.png', name: 'Canadian Dollar' },
  CNY : { id: 5, src: './flags/china.png', name: 'Chinese Yuan Renminbi' },
  HRK : { id: 6, src: './flags/croatia.png', name: 'Croatian Kuna' },
  CZK : { id: 7, src: './flags/czech-republic.png', name: 'Czech Koruna' },
  DKK : { id: 8, src: './flags/denmark.png', name: 'Danish Krone' },
  EUR : { id: 9, src: './flags/european-union.png', name: 'Euro' },
  HKD : { id: 10, src: './flags/hong-kong.png', name: 'Hong Kong Dollar' },
  HUF : { id: 11, src: './flags/hungary.png', name: 'Hungarian Forint' },
  ISK : { id: 12, src: './flags/iceland.png', name: 'Icelandic Króna' },
  INR : { id: 13, src: './flags/india.png', name: 'Indian Rupee' },
  IDR : { id: 14, src: './flags/indonesia.png', name: 'Indonesian Rupiah' },
  ILS : { id: 15, src: './flags/israel.png', name: 'Israeli New Shekel' },
  JPY : { id: 16, src: './flags/japan.png', name: 'Japanese Yen' },
  MYR : { id: 17, src: './flags/malaysia.png', name: 'Malaysian Ringgit' },
  MXN : { id: 18, src: './flags/mexico.png', name: 'Mexican Peso' },
  NZD : { id: 19, src: './flags/new-zealand.png', name: 'New Zealand Dollar' },
  NOK : { id: 20, src: './flags/norway.png', name: 'Norwegian Krone' },
  PHP : { id: 21, src: './flags/philippines.png', name: 'Philippine Peso' },
  PLN : { id: 22, src: './flags/republic-of-poland.png', name: 'Polish Zloty' },
  RON : { id: 23, src: './flags/romania.png', name: 'Romanian Leu' },
  RUB : { id: 24, src: './flags/russia.png', name: 'Russian Ruble' },
  SGD : { id: 25, src: './flags/singapore.png', name: 'Singapore Dollar' },
  ZAR : { id: 26, src: './flags/south-africa.png', name: 'South African Rand' },
  KRW : { id: 27, src: './flags/south-korea.png', name: 'South Korean Won' },
  SEK : { id: 28, src: './flags/sweden.png', name: 'Swedish Krona' },
  CHF : { id: 29, src: './flags/switzerland.png', name: 'Swiss Franc' },
  THB : { id: 30, src: './flags/thailand.png', name: 'Thai Baht' },
  TRY : { id: 31, src: './flags/turkey.png', name: 'Turkish Lira' },
  GBP : { id: 32, src: './flags/united-kingdom.png', name: 'British Pound' },
  USD : { id: 33, src: './flags/united-states-of-america.png', name: 'US Dollar' },
};

export default flaglabel;
